version: '3.8'
services:
  server:
    image: ${PROJECT_NAME}/server
    volumes:
      - ../server/src:/usr/app/packages/server/src
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '8080:80'
