version: '3.8'
services:
  server:
    image: ${PROJECT_NAME}/server
    volumes:
      - ../server/src:/usr/app/packages/server/src
    environment:
      POSTGRES: postgresql://postgres:postgres@timescale:5432/${PROJECT_NAME}
      GOOGLE_OAUTH2_CLIENT_ID: test.apps.googleusercontent.com
      GOOGLE_OAUTH2_CLIENT_SECRET: test
      GOOGLE_OAUTH2_REDIRECT_URI: http://localhost:8080/auth/redirect/google
      GOOGLE_OAUTH2_AUTH_BASE_URL: http://nginx/google/oauth2/auth
      GOOGLE_OAUTH2_TOKEN_URL: http://nginx/google/oauth2/token
    depends_on:
      - timescale

  nginx:
    image: nginx:1.22
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '8080:80'
    depends_on:
      - server
      - google_stub

  mqtt:
    image: eclipse-mosquitto:2.0
    ports:
      - '1883:1883'
    command: 'mosquitto -c /mosquitto-no-auth.conf'

  timescale:
    image: timescale/timescaledb:2.7.0-pg14
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ${PROJECT_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  google_stub:
    image: ${PROJECT_NAME}/google-stub
    volumes:
      - ../google-stub/src:/usr/app/packages/google-stub/src
    environment:
      OAUTH2_CLIENT_ID: test.apps.googleusercontent.com
      OAUTH2_CLIENT_SECRET: test

volumes:
  postgres_data:
