version: '3.8'
services:
  server:
    image: ${PROJECT_NAME}/server
    volumes:
      - ../server/config:/usr/app/packages/server/config
      - ../server/src:/usr/app/packages/server/src
    environment:
      - POSTGRES=postgresql://postgres:postgres@timescale:5432/${PROJECT_NAME}
  nginx:
    image: nginx:1.22
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '8080:80'
  mqtt:
    image: eclipse-mosquitto:2.0
    ports:
      - '1883:1883'
    command: 'mosquitto -c /mosquitto-no-auth.conf'
  timescale:
    image: timescale/timescaledb:2.7.0-pg14
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=password
