ports:
  - name: Nginx
    port: 8080
    onOpen: ignore
    visibility: public
  - name: TimescaleDB
    port: 5432
    onOpen: ignore
    visibility: public
  - name: Mosquitto
    port: 1883
    onOpen: ignore
    visibility: public

tasks:
  - before: yarn script build
  - init: yarn script start

github:
  prebuilds:
    master: true
    branches: false
    pullRequests: true
    pullRequestsFromForks: false
    addCheck: false
    addComment: false
    addBadge: true
