ports:
  - name: Nginx
    port: 8080
    onOpen: ignore
    visibility: public
  - name: TimescaleDB
    port: 5432
    onOpen: ignore
    visibility: public
  - name: PgAdmin
    port: 5050
    onOpen: ignore
    visibility: public
  - name: Mosquitto
    port: 1883
    onOpen: ignore
    visibility: public

tasks:
  - init: yarn install
  - command: yarn script dev -b

github:
  prebuilds:
    master: true
    branches: false
    pullRequests: true
    pullRequestsFromForks: false
    addCheck: false
    addComment: false
    addBadge: true
