ports:
  - name: Nginx
    port: 8080
    onOpen: ignore
    visibility: public
  - name: TimescaleDB
    port: 5432
    onOpen: ignore
    visibility: public
  - name: Mosquitto
    port: 1883
    onOpen: ignore
    visibility: public

tasks:
  - before: |
      sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
      yarn script build --no-production --nodeEnv development

  - init: yarn script dev

github:
  prebuilds:
    master: true
    branches: false
    pullRequests: true
    pullRequestsFromForks: false
    addCheck: false
    addComment: false
    addBadge: true
