packageExtensions:
  esbuild-plugin-pino@2.0.0:
    dependencies:
      pino: "npm:pino@8.12.1"
      pino-pretty: "npm:pino-pretty@10.0.0"
      pino-roll: "npm:pino-roll@1.0.0-rc.1"
      thread-stream: "npm:thread-stream@2.3.0"
  qqjs@0.3.11:
    dependencies:
      tslib: "npm:tslib@2.4.0"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.5.0.cjs
