packageExtensions:
  chalk@5.0.1:
    dependencies:
      '#ansi-styles': 'npm:ansi-styles@6.1.0'
      '#supports-color': 'npm:supports-color@9.2.2'
  qqjs@0.3.11:
    dependencies:
      tslib: 'npm:tslib@2.4.0'
  esbuild-plugin-pino@1.2.5:
    dependencies:
      pino: 'npm:pino@8.7.0'
      pino-pretty: 'npm:pino-pretty@9.1.1'
      pino-roll: 'npm:pino-roll@1.0.0-rc.1'
      thread-stream: 'npm:thread-stream@2.0.1'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'

yarnPath: .yarn/releases/yarn-3.2.3.cjs
