version: '3.8'
services:
  server:
    image: ${IMAGE_REPO}/iot-server
    restart: unless-stopped
    environment:
      POSTGRES: ${POSTGRES}
      GOOGLE_OAUTH2_CLIENT_ID: ${GOOGLE_OAUTH2_CLIENT_ID}
      GOOGLE_OAUTH2_CLIENT_SECRET: ${GOOGLE_OAUTH2_CLIENT_SECRET}
      GOOGLE_OAUTH2_REDIRECT_URI: ${GOOGLE_OAUTH2_REDIRECT_URI}
      JWT_SECRET: ${JWT_SECRET}
      ROOT_USER_EMAIL: ${ROOT_USER_EMAIL}
      MQTT: ${MOSQUITTO}
      TIME_ZONE: ${TZ}
    depends_on:
      - mosquitto
      - timescale
      - zigbee2mqtt

  frontend:
    image: ${IMAGE_REPO}/iot-frontend
    restart: unless-stopped

  zigbee2mqtt:
    image: koenkk/zigbee2mqtt:1.30.3
    restart: unless-stopped
    volumes:
      - zigbee2mqtt_data:/app/data
      - ./zigbee2mqtt-configuration.yaml:/app/data/configuration.yaml
    ports:
      - 8080:8080
    devices:
      - ${ZIGBEE_ADAPTER_LOCATION}:/dev/ttyUSB0

  nginx:
    image: nginx:1.22
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  mosquitto:
    image: eclipse-mosquitto:2.0
    restart: unless-stopped
    ports:
      - 1883:1883
    environment:
      MOSQUITTO_USERNAME: ${MOSQUITTO_USERNAME}
      MOSQUITTO_PASSWORD: ${MOSQUITTO_PASSWORD}
    volumes:
      - mosquitto_data:/mosquitto/data
      - ./mosquitto-entrypoint.sh:/docker-entrypoint.sh
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

  timescale:
    image: timescale/timescaledb:2.7.0-pg14
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${PROJECT_NAME}

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  mosquitto_data:
  zigbee2mqtt_data:
