homeassistant: false
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: ${MOSQUITTO}
serial:
  port: ${ZIGBEE_ADAPTER_LOCATION}
advanced:
  homeassistant_legacy_entity_attributes: false
  legacy_api: false
  legacy_availability_payload: false
  log_level: info
  network_key: GENERATE
  pan_id: GENERATE
device_options:
  legacy: false
frontend: true
devices: devices.yaml
groups: groups.yaml
