version: '3.8'
services:
  server:
    image: ${PROJECT_NAME}/server:${IMAGE_TAG}
    volumes:
      - ../../server/src:/usr/app/packages/server/src
      - ../../server/config:/usr/app/packages/server/config
      - ../../common-application/src:/usr/app/packages/common-application/src
      - ../../common-errors/src:/usr/app/packages/common-errors/src
      - ../../common-logger/src:/usr/app/packages/common-logger/src
      - ../../common-config/src:/usr/app/packages/common-config/src
    environment:
      POSTGRES: postgresql://postgres:postgres@timescale:5432/${PROJECT_NAME}
      GOOGLE_OAUTH2_CLIENT_ID: test.apps.googleusercontent.com
      GOOGLE_OAUTH2_CLIENT_SECRET: test
      GOOGLE_OAUTH2_REDIRECT_URI: http://localhost:8080/auth/redirect/google
      GOOGLE_OAUTH2_AUTH_BASE_URL: http://nginx:8080/google/oauth2/auth
      GOOGLE_OAUTH2_TOKEN_URL: http://nginx:8080/google/oauth2/token
      JWT_SECRET: secret
      ROOT_USER_EMAIL: test@example.com
      MQTT: mqtt://mqtt:1883
      TIME_ZONE: ${TZ}
    depends_on:
      - timescale

  frontend:
    image: ${PROJECT_NAME}/frontend:${IMAGE_TAG}
    volumes:
      - ../../frontend/public:/usr/app/packages/frontend/public
      - ../../frontend/src:/usr/app/packages/frontend/src
      - ../../frontend/index.html:/usr/app/packages/frontend/index.html
      - ../../frontend/vite.config.ts:/usr/app/packages/frontend/vite.config.ts

  nginx:
    image: nginx:1.22
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:8080
    depends_on:
      - server
      - google_stub
      - frontend

  mqtt:
    image: eclipse-mosquitto:2.0
    ports:
      - 1883:1883
    command: 'mosquitto -c /mosquitto-no-auth.conf'

  timescale:
    image: timescale/timescaledb:2.7.0-pg14
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ${PROJECT_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  google_stub:
    image: ${PROJECT_NAME}/google-stub
    volumes:
      - ../../google-stub/src:/usr/app/packages/google-stub/src
      - ../../google-stub/config:/usr/app/packages/google-stub/config
    environment:
      OAUTH2_CLIENT_ID: test.apps.googleusercontent.com
      OAUTH2_CLIENT_SECRET: test

  tests:
    image: ${PROJECT_NAME}/tests
    volumes:
      - ../../tests/config:/usr/app/packages/tests/config
      - ../../tests/src:/usr/app/packages/tests/src
    profiles:
      - tests
    environment:
      FORCE_COLOR: true # https://github.com/facebook/jest/issues/3877
      JWT_SECRET: secret
      NODE_OPTIONS: --experimental-vm-modules
      NODE_NO_WARNINGS: 1

volumes:
  postgres_data:
