export const generateDevicesPayload = () => [
    {
        definition: null,
        endpoints: {
            1: { bindings: [], clusters: { input: [], output: [] }, configured_reportings: [], scenes: [] },
            10: { bindings: [], clusters: { input: [], output: [] }, configured_reportings: [], scenes: [] },
            11: {
                bindings: [],
                clusters: { input: ['ssIasAce', 'genTime'], output: ['ssIasZone', 'ssIasWd'] },
                configured_reportings: [],
                scenes: [],
            },
            110: { bindings: [], clusters: { input: [], output: [] }, configured_reportings: [], scenes: [] },
            12: { bindings: [], clusters: { input: [], output: [] }, configured_reportings: [], scenes: [] },
            13: { bindings: [], clusters: { input: ['genOta'], output: [] }, configured_reportings: [], scenes: [] },
            2: { bindings: [], clusters: { input: [], output: [] }, configured_reportings: [], scenes: [] },
            242: { bindings: [], clusters: { input: [], output: [] }, configured_reportings: [], scenes: [] },
            3: { bindings: [], clusters: { input: [], output: [] }, configured_reportings: [], scenes: [] },
            4: { bindings: [], clusters: { input: [], output: [] }, configured_reportings: [], scenes: [] },
            47: { bindings: [], clusters: { input: [], output: [] }, configured_reportings: [], scenes: [] },
            5: { bindings: [], clusters: { input: [], output: [] }, configured_reportings: [], scenes: [] },
            6: { bindings: [], clusters: { input: [], output: [] }, configured_reportings: [], scenes: [] },
            8: { bindings: [], clusters: { input: [], output: [] }, configured_reportings: [], scenes: [] },
        },
        friendly_name: 'Coordinator',
        ieee_address: '0x00124b0024c2d3a6',
        interview_completed: true,
        interviewing: false,
        network_address: 0,
        supported: false,
        type: 'Coordinator',
    },
    {
        date_code: '',
        definition: {
            description: 'Motion sensor',
            exposes: [
                {
                    access: 1,
                    description: 'Indicates whether the device detected occupancy',
                    name: 'occupancy',
                    property: 'occupancy',
                    type: 'binary',
                    value_off: false,
                    value_on: true,
                },
                {
                    access: 1,
                    description: 'Indicates if the battery of this device is almost empty',
                    name: 'battery_low',
                    property: 'battery_low',
                    type: 'binary',
                    value_off: false,
                    value_on: true,
                },
                {
                    access: 1,
                    description: 'Indicates whether the device is tampered',
                    name: 'tamper',
                    property: 'tamper',
                    type: 'binary',
                    value_off: false,
                    value_on: true,
                },
                {
                    access: 1,
                    description: 'Remaining battery in %',
                    name: 'battery',
                    property: 'battery',
                    type: 'numeric',
                    unit: '%',
                    value_max: 100,
                    value_min: 0,
                },
                {
                    access: 1,
                    description: 'Link quality (signal strength)',
                    name: 'linkquality',
                    property: 'linkquality',
                    type: 'numeric',
                    unit: 'lqi',
                    value_max: 255,
                    value_min: 0,
                },
            ],
            model: 'TS0202',
            options: [],
            supports_ota: false,
            vendor: 'TuYa',
        },
        endpoints: {
            1: {
                bindings: [],
                clusters: {
                    input: ['genPowerCfg', 'ssIasZone', 'genIdentify', 'genBasic'],
                    output: ['touchlink', 'genOnOff', 'genOta', 'genTime'],
                },
                configured_reportings: [],
                scenes: [],
            },
        },
        friendly_name: '0xa4c138c1736f8e64',
        ieee_address: '0xa4c138c1736f8e64',
        interview_completed: true,
        interviewing: false,
        manufacturer: '_TZ3000_wrgn6xrz',
        model_id: 'TS0202',
        network_address: 54131,
        power_source: 'Battery',
        supported: true,
        type: 'EndDevice',
    },
    {
        date_code: '20201026',
        definition: {
            description: 'Temperature and humidity sensor',
            exposes: [
                {
                    access: 1,
                    description: 'Remaining battery in %',
                    name: 'battery',
                    property: 'battery',
                    type: 'numeric',
                    unit: '%',
                    value_max: 100,
                    value_min: 0,
                },
                {
                    access: 1,
                    description: 'Measured temperature value',
                    name: 'temperature',
                    property: 'temperature',
                    type: 'numeric',
                    unit: '°C',
                },
                {
                    access: 1,
                    description: 'Measured relative humidity',
                    name: 'humidity',
                    property: 'humidity',
                    type: 'numeric',
                    unit: '%',
                },
                {
                    access: 1,
                    description: 'Voltage of the battery in millivolts',
                    name: 'voltage',
                    property: 'voltage',
                    type: 'numeric',
                    unit: 'mV',
                },
                {
                    access: 1,
                    description: 'Link quality (signal strength)',
                    name: 'linkquality',
                    property: 'linkquality',
                    type: 'numeric',
                    unit: 'lqi',
                    value_max: 255,
                    value_min: 0,
                },
            ],
            model: 'SNZB-02',
            options: [
                {
                    access: 2,
                    description:
                        'Number of digits after decimal point for temperature, takes into effect on next report of device.',
                    name: 'temperature_precision',
                    property: 'temperature_precision',
                    type: 'numeric',
                    value_max: 3,
                    value_min: 0,
                },
                {
                    access: 2,
                    description:
                        'Calibrates the temperature value (absolute offset), takes into effect on next report of device.',
                    name: 'temperature_calibration',
                    property: 'temperature_calibration',
                    type: 'numeric',
                },
                {
                    access: 2,
                    description:
                        'Number of digits after decimal point for humidity, takes into effect on next report of device.',
                    name: 'humidity_precision',
                    property: 'humidity_precision',
                    type: 'numeric',
                    value_max: 3,
                    value_min: 0,
                },
                {
                    access: 2,
                    description:
                        'Calibrates the humidity value (absolute offset), takes into effect on next report of device.',
                    name: 'humidity_calibration',
                    property: 'humidity_calibration',
                    type: 'numeric',
                },
            ],
            supports_ota: false,
            vendor: 'SONOFF',
        },
        endpoints: {
            1: {
                bindings: [
                    {
                        cluster: 'msTemperatureMeasurement',
                        target: { endpoint: 1, ieee_address: '0x00124b0024c2d3a6', type: 'endpoint' },
                    },
                    {
                        cluster: 'msRelativeHumidity',
                        target: { endpoint: 1, ieee_address: '0x00124b0024c2d3a6', type: 'endpoint' },
                    },
                    {
                        cluster: 'genPowerCfg',
                        target: { endpoint: 1, ieee_address: '0x00124b0024c2d3a6', type: 'endpoint' },
                    },
                ],
                clusters: {
                    input: ['genBasic', 'genIdentify', 'msTemperatureMeasurement', 'msRelativeHumidity', 'genPowerCfg'],
                    output: ['genIdentify'],
                },
                configured_reportings: [
                    {
                        attribute: 'measuredValue',
                        cluster: 'msTemperatureMeasurement',
                        maximum_report_interval: 1800,
                        minimum_report_interval: 5,
                        reportable_change: 20,
                    },
                    {
                        attribute: 'measuredValue',
                        cluster: 'msRelativeHumidity',
                        maximum_report_interval: 3600,
                        minimum_report_interval: 10,
                        reportable_change: 100,
                    },
                    {
                        attribute: 'batteryVoltage',
                        cluster: 'genPowerCfg',
                        maximum_report_interval: 62000,
                        minimum_report_interval: 3600,
                        reportable_change: 0,
                    },
                    {
                        attribute: 'batteryPercentageRemaining',
                        cluster: 'genPowerCfg',
                        maximum_report_interval: 62000,
                        minimum_report_interval: 3600,
                        reportable_change: 0,
                    },
                ],
                scenes: [],
            },
        },
        friendly_name: '0x00124b002520d73f',
        ieee_address: '0x00124b002520d73f',
        interview_completed: true,
        interviewing: false,
        manufacturer: 'eWeLink',
        model_id: 'TH01',
        network_address: 15068,
        power_source: 'Battery',
        supported: true,
        type: 'EndDevice',
    },
    {
        date_code: '20211103',
        definition: {
            description: 'Contact sensor',
            exposes: [
                {
                    access: 1,
                    description: 'Indicates if the contact is closed (= true) or open (= false)',
                    name: 'contact',
                    property: 'contact',
                    type: 'binary',
                    value_off: true,
                    value_on: false,
                },
                {
                    access: 1,
                    description: 'Indicates if the battery of this device is almost empty',
                    name: 'battery_low',
                    property: 'battery_low',
                    type: 'binary',
                    value_off: false,
                    value_on: true,
                },
                {
                    access: 1,
                    description: 'Remaining battery in %',
                    name: 'battery',
                    property: 'battery',
                    type: 'numeric',
                    unit: '%',
                    value_max: 100,
                    value_min: 0,
                },
                {
                    access: 1,
                    description: 'Voltage of the battery in millivolts',
                    name: 'voltage',
                    property: 'voltage',
                    type: 'numeric',
                    unit: 'mV',
                },
                {
                    access: 1,
                    description: 'Link quality (signal strength)',
                    name: 'linkquality',
                    property: 'linkquality',
                    type: 'numeric',
                    unit: 'lqi',
                    value_max: 255,
                    value_min: 0,
                },
            ],
            model: 'SNZB-04',
            options: [],
            supports_ota: false,
            vendor: 'SONOFF',
        },
        endpoints: {
            1: {
                bindings: [
                    {
                        cluster: 'genPowerCfg',
                        target: { endpoint: 1, ieee_address: '0x00124b0024c2d3a6', type: 'endpoint' },
                    },
                ],
                clusters: { input: ['genBasic', 'genIdentify', 'ssIasZone', 'genPowerCfg'], output: ['genIdentify'] },
                configured_reportings: [
                    {
                        attribute: 'batteryVoltage',
                        cluster: 'genPowerCfg',
                        maximum_report_interval: 62000,
                        minimum_report_interval: 3600,
                        reportable_change: 0,
                    },
                    {
                        attribute: 'batteryPercentageRemaining',
                        cluster: 'genPowerCfg',
                        maximum_report_interval: 62000,
                        minimum_report_interval: 3600,
                        reportable_change: 0,
                    },
                ],
                scenes: [],
            },
        },
        friendly_name: '0x00124b0025192efe',
        ieee_address: '0x00124b0025192efe',
        interview_completed: true,
        interviewing: false,
        manufacturer: 'eWeLink',
        model_id: 'DS01',
        network_address: 23180,
        power_source: 'Battery',
        supported: true,
        type: 'EndDevice',
    },
    {
        date_code: '',
        definition: {
            description: 'Temperature & humidity & illuminance sensor with display',
            exposes: [
                {
                    access: 1,
                    description: 'Measured temperature value',
                    name: 'temperature',
                    property: 'temperature',
                    type: 'numeric',
                    unit: '°C',
                },
                {
                    access: 1,
                    description: 'Measured relative humidity',
                    name: 'humidity',
                    property: 'humidity',
                    type: 'numeric',
                    unit: '%',
                },
                {
                    access: 1,
                    description: 'Remaining battery in %',
                    name: 'battery',
                    property: 'battery',
                    type: 'numeric',
                    unit: '%',
                    value_max: 100,
                    value_min: 0,
                },
                {
                    access: 1,
                    description: 'Raw measured illuminance',
                    name: 'illuminance',
                    property: 'illuminance',
                    type: 'numeric',
                },
                {
                    access: 1,
                    description: 'Measured illuminance in lux',
                    name: 'illuminance_lux',
                    property: 'illuminance_lux',
                    type: 'numeric',
                    unit: 'lx',
                },
                {
                    access: 3,
                    description: 'Alarm temperature max',
                    name: 'alarm_temperature_max',
                    property: 'alarm_temperature_max',
                    type: 'numeric',
                    unit: '°C',
                    value_max: 80,
                    value_min: -20,
                },
                {
                    access: 3,
                    description: 'Alarm temperature min',
                    name: 'alarm_temperature_min',
                    property: 'alarm_temperature_min',
                    type: 'numeric',
                    unit: '°C',
                    value_max: 80,
                    value_min: -20,
                },
                {
                    access: 3,
                    description: 'Alarm humidity max',
                    name: 'alarm_humidity_max',
                    property: 'alarm_humidity_max',
                    type: 'numeric',
                    unit: '%',
                    value_max: 100,
                    value_min: 0,
                },
                {
                    access: 3,
                    description: 'Alarm humidity min',
                    name: 'alarm_humidity_min',
                    property: 'alarm_humidity_min',
                    type: 'numeric',
                    unit: '%',
                    value_max: 100,
                    value_min: 0,
                },
                {
                    access: 1,
                    description: 'Alarm humidity status',
                    name: 'alarm_humidity',
                    property: 'alarm_humidity',
                    type: 'enum',
                    values: ['below_min_humdity', 'over_humidity', 'off'],
                },
                {
                    access: 1,
                    description: 'Alarm temperature status',
                    name: 'alarm_temperature',
                    property: 'alarm_temperature',
                    type: 'enum',
                    values: ['below_min_temperature', 'over_temperature', 'off'],
                },
                {
                    access: 1,
                    description: 'Link quality (signal strength)',
                    name: 'linkquality',
                    property: 'linkquality',
                    type: 'numeric',
                    unit: 'lqi',
                    value_max: 255,
                    value_min: 0,
                },
            ],
            model: 'LCZ030',
            options: [
                {
                    access: 2,
                    description:
                        'Number of digits after decimal point for illuminance, takes into effect on next report of device.',
                    name: 'illuminance_precision',
                    property: 'illuminance_precision',
                    type: 'numeric',
                    value_max: 3,
                    value_min: 0,
                },
                {
                    access: 2,
                    description:
                        'Calibrates the illuminance value (percentual offset), takes into effect on next report of device.',
                    name: 'illuminance_calibration',
                    property: 'illuminance_calibration',
                    type: 'numeric',
                },
                {
                    access: 2,
                    description:
                        'Number of digits after decimal point for illuminance_lux, takes into effect on next report of device.',
                    name: 'illuminance_lux_precision',
                    property: 'illuminance_lux_precision',
                    type: 'numeric',
                    value_max: 3,
                    value_min: 0,
                },
                {
                    access: 2,
                    description:
                        'Calibrates the illuminance_lux value (percentual offset), takes into effect on next report of device.',
                    name: 'illuminance_lux_calibration',
                    property: 'illuminance_lux_calibration',
                    type: 'numeric',
                },
                {
                    access: 2,
                    description:
                        'Number of digits after decimal point for temperature, takes into effect on next report of device.',
                    name: 'temperature_precision',
                    property: 'temperature_precision',
                    type: 'numeric',
                    value_max: 3,
                    value_min: 0,
                },
                {
                    access: 2,
                    description:
                        'Calibrates the temperature value (absolute offset), takes into effect on next report of device.',
                    name: 'temperature_calibration',
                    property: 'temperature_calibration',
                    type: 'numeric',
                },
                {
                    access: 2,
                    description:
                        'Number of digits after decimal point for humidity, takes into effect on next report of device.',
                    name: 'humidity_precision',
                    property: 'humidity_precision',
                    type: 'numeric',
                    value_max: 3,
                    value_min: 0,
                },
                {
                    access: 2,
                    description:
                        'Calibrates the humidity value (absolute offset), takes into effect on next report of device.',
                    name: 'humidity_calibration',
                    property: 'humidity_calibration',
                    type: 'numeric',
                },
            ],
            supports_ota: false,
            vendor: 'TuYa',
        },
        endpoints: {
            1: {
                bindings: [
                    {
                        cluster: 'genBasic',
                        target: { endpoint: 1, ieee_address: '0x00124b0024c2d3a6', type: 'endpoint' },
                    },
                    {
                        cluster: 'genPowerCfg',
                        target: { endpoint: 1, ieee_address: '0x00124b0024c2d3a6', type: 'endpoint' },
                    },
                    {
                        cluster: 'msTemperatureMeasurement',
                        target: { endpoint: 1, ieee_address: '0x00124b0024c2d3a6', type: 'endpoint' },
                    },
                    {
                        cluster: 'msIlluminanceMeasurement',
                        target: { endpoint: 1, ieee_address: '0x00124b0024c2d3a6', type: 'endpoint' },
                    },
                    {
                        cluster: 'msRelativeHumidity',
                        target: { endpoint: 1, ieee_address: '0x00124b0024c2d3a6', type: 'endpoint' },
                    },
                    {
                        cluster: 'manuSpecificTuya_2',
                        target: { endpoint: 1, ieee_address: '0x00124b0024c2d3a6', type: 'endpoint' },
                    },
                ],
                clusters: {
                    input: ['genBasic', 'genPowerCfg', 'msIlluminanceMeasurement', 'manuSpecificTuya_2'],
                    output: ['genOta', 'genTime'],
                },
                configured_reportings: [],
                scenes: [],
            },
            2: { bindings: [], clusters: { input: [], output: [] }, configured_reportings: [], scenes: [] },
        },
        friendly_name: '0xcc86ecfffec89545',
        ieee_address: '0xcc86ecfffec89545',
        interview_completed: true,
        interviewing: false,
        manufacturer: '_TZ3000_qaaysllp',
        model_id: 'TS0201',
        network_address: 53331,
        power_source: 'Battery',
        supported: true,
        type: 'EndDevice',
    },
    {
        date_code: '',
        definition: {
            description: 'Smart plug (with power monitoring by polling)',
            exposes: [
                {
                    features: [
                        {
                            access: 7,
                            description: 'On/off state of the switch',
                            name: 'state',
                            property: 'state',
                            type: 'binary',
                            value_off: 'OFF',
                            value_on: 'ON',
                            value_toggle: 'TOGGLE',
                        },
                    ],
                    type: 'switch',
                },
                {
                    access: 1,
                    description: 'Instantaneous measured power',
                    name: 'power',
                    property: 'power',
                    type: 'numeric',
                    unit: 'W',
                },
                {
                    access: 1,
                    description: 'Instantaneous measured electrical current',
                    name: 'current',
                    property: 'current',
                    type: 'numeric',
                    unit: 'A',
                },
                {
                    access: 1,
                    description: 'Measured electrical potential value',
                    name: 'voltage',
                    property: 'voltage',
                    type: 'numeric',
                    unit: 'V',
                },
                {
                    access: 1,
                    description: 'Sum of consumed energy',
                    name: 'energy',
                    property: 'energy',
                    type: 'numeric',
                    unit: 'kWh',
                },
                {
                    access: 3,
                    description: 'Recover state after power outage',
                    name: 'power_outage_memory',
                    property: 'power_outage_memory',
                    type: 'enum',
                    values: ['on', 'off', 'restore'],
                },
                {
                    access: 7,
                    description: 'Plug LED indicator mode',
                    name: 'indicator_mode',
                    property: 'indicator_mode',
                    type: 'enum',
                    values: ['off', 'off/on', 'on/off', 'on'],
                },
                {
                    features: [
                        {
                            access: 3,
                            description: 'Enables/disables physical input on the device',
                            name: 'state',
                            property: 'child_lock',
                            type: 'binary',
                            value_off: 'UNLOCK',
                            value_on: 'LOCK',
                        },
                    ],
                    type: 'lock',
                },
                {
                    access: 1,
                    description: 'Link quality (signal strength)',
                    name: 'linkquality',
                    property: 'linkquality',
                    type: 'numeric',
                    unit: 'lqi',
                    value_max: 255,
                    value_min: 0,
                },
            ],
            model: 'TS011F_plug_3',
            options: [
                {
                    access: 2,
                    description:
                        'This device does not support reporting electric measurements so it is polled instead. The default poll interval is 60 seconds, set to -1 to disable.',
                    name: 'measurement_poll_interval',
                    property: 'measurement_poll_interval',
                    type: 'numeric',
                    value_min: -1,
                },
                {
                    access: 2,
                    description:
                        'Calibrates the power value (percentual offset), takes into effect on next report of device.',
                    name: 'power_calibration',
                    property: 'power_calibration',
                    type: 'numeric',
                },
                {
                    access: 2,
                    description:
                        'Calibrates the current value (percentual offset), takes into effect on next report of device.',
                    name: 'current_calibration',
                    property: 'current_calibration',
                    type: 'numeric',
                },
                {
                    access: 2,
                    description:
                        'Calibrates the voltage value (percentual offset), takes into effect on next report of device.',
                    name: 'voltage_calibration',
                    property: 'voltage_calibration',
                    type: 'numeric',
                },
            ],
            supports_ota: true,
            vendor: 'TuYa',
        },
        endpoints: {
            1: {
                bindings: [],
                clusters: {
                    input: [
                        'genIdentify',
                        'genGroups',
                        'genScenes',
                        'genOnOff',
                        'seMetering',
                        'haElectricalMeasurement',
                        'manuSpecificTuya_3',
                        '57344',
                        'genBasic',
                    ],
                    output: ['genOta', 'genTime'],
                },
                configured_reportings: [],
                scenes: [],
            },
            242: {
                bindings: [],
                clusters: { input: [], output: ['greenPower'] },
                configured_reportings: [],
                scenes: [],
            },
        },
        friendly_name: '0xa4c13810c32463fb',
        ieee_address: '0xa4c13810c32463fb',
        interview_completed: true,
        interviewing: false,
        manufacturer: '_TZ3000_gjnozsaz',
        model_id: 'TS011F',
        network_address: 54544,
        power_source: 'Mains (single phase)',
        supported: true,
        type: 'Router',
    },
    {
        date_code: '',
        definition: {
            description: 'Smart light switch - 1 gang',
            exposes: [
                {
                    features: [
                        {
                            access: 7,
                            description: 'On/off state of the switch',
                            name: 'state',
                            property: 'state',
                            type: 'binary',
                            value_off: 'OFF',
                            value_on: 'ON',
                            value_toggle: 'TOGGLE',
                        },
                    ],
                    type: 'switch',
                },
                {
                    access: 1,
                    description: 'Link quality (signal strength)',
                    name: 'linkquality',
                    property: 'linkquality',
                    type: 'numeric',
                    unit: 'lqi',
                    value_max: 255,
                    value_min: 0,
                },
            ],
            model: 'TS0011',
            options: [],
            supports_ota: false,
            vendor: 'TuYa',
        },
        endpoints: {
            1: {
                bindings: [
                    {
                        cluster: 'genOnOff',
                        target: { endpoint: 1, ieee_address: '0x00124b0024c2d3a6', type: 'endpoint' },
                    },
                ],
                clusters: { input: ['genBasic', 'genGroups', 'genScenes', 'genOnOff'], output: ['genOta', 'genTime'] },
                configured_reportings: [],
                scenes: [],
            },
        },
        friendly_name: '0x804b50fffe49f1ca',
        ieee_address: '0x804b50fffe49f1ca',
        interview_completed: true,
        interviewing: false,
        manufacturer: '_TYZB01_7pytyxfm',
        model_id: 'TS0011',
        network_address: 61782,
        power_source: 'Mains (single phase)',
        supported: true,
        type: 'EndDevice',
    },
];
