name: CI

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '*.md'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: yarn install
      - name: Build the stack
        run: yarn script build --onlyServer=false
      - name: Start containers
        run: yarn script start --env=local
      - name: Run tests
        run: yarn script test
      - name: Stop containers
        if: always()
        run: yarn script stop --env=local
