name: CI

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '*.md'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.md'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Build the stack
        run: yarn script build
      - name: Start containers
        run: yarn script start
      - name: Run tests
        run: yarn script test
      - name: Stop containers
        run: yarn script stop
