name: Frontend CI

on:
  push:
    paths:
      - 'packages/frontend/**'

env:
  IMAGE_TAG: latest
  IMAGE_REPO: ${{ secrets.DOCKER_USERNAME }}
  PLATFORMS: linux/amd64,linux/arm64

jobs:
  ci:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn install

      - name: Build the stack
        run: yarn script build -a frontend

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        if: github.ref == 'refs/heads/main'
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push image
        if: github.ref == 'refs/heads/main'
        run: yarn script pushImage server
