name: Server CI

on: [push]

# on:
#   push:
#     paths:
#       - 'packages/server/**'
#       - 'packages/common-*/**'

env:
  IMAGE_TAG: latest
  IMAGE_REPO: ${{ secrets.DOCKER_USERNAME }}

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn install

      - name: Build the stack
        run: yarn script build

      - name: Start containers
        run: yarn script start

      - name: Run tests
        run: yarn script test

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: serverImage
          path: /tmp/serverImage.tar

  publish:
    name: Publish Docker image
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: serverImage
          path: /tmp

      - name: Load image
        run: docker load --input /tmp/serverImage.tar

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: yarn script pushImage server
