name: Server CI

on:
  push:
    paths:
      - '*'
      # - 'packages/server/**'
      # - 'packages/common-*/**'

env:
  TAG: ${{ secrets.DOCKER_USERNAME }}/iot-server:latest

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn install

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          tags: ${{ env.TAG }}
          file: ./packages/server/Dockerfile
          load: true
          outputs: type=docker,dest=/tmp/frontendImage.tar

      - name: Start containers
        run: yarn script start --imageTag=${{ env.TAG }}

      - name: Run tests
        run: yarn script test

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: frontendImage
          path: /tmp/frontendImage.tar

  publish:
    name: Publish Docker image
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Load image
        run: docker load --input /tmp/frontendImage.tar

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: docker image push ${{ env.TAG }}
