name: Server CI

on: [push]

# on:
#   push:
#     paths:
#       - 'packages/server/**'
#       - 'packages/common-*/**'

env:
  IMAGE_TAG: latest
  IMAGE_REPO: ${{ secrets.DOCKER_USERNAME }}

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    env:
      APPS: server,google_stub,tests
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn install

      - name: Build the stack
        run: yarn script build

      - name: Start containers
        run: yarn script start

      - name: Run tests
        run: yarn script test

  publish:
    name: Publish Docker image
    runs-on: ubuntu-latest
    needs: tests
    if: github.ref == 'refs/heads/main'
    env:
      APPS: server
      PLATFORMS: linux/amd64,linux/arm64
    steps:
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Install dependencies
        run: yarn install

      - name: Build the image
        run: yarn script build

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push image
        run: yarn script pushImage server
