name: Server CI

on:
  push:
    paths:
      - 'packages/server/**'
      - 'packages/common-*/**'

env:
  TAG: ${{ secrets.DOCKER_USERNAME }}/iot-server:latest

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn install

      - name: Build Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          tags: ${{ env.TAG }}
          load: true

      - name: Start containers
        run: yarn script start --imageTag=${{ env.TAG }}

      - name: Run tests
        run: yarn script test

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.TAG }}
          push: true
